<?php

namespace Database\Seeders;

use App\Models\Role;
use App\Models\User;
use App\Models\HomeBlock;
use App\Models\Testimonial;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $developerRole = Role::query()->updateOrCreate(
            ['name' => 'developer'],
            ['description' => 'Acceso completo al sistema administrativo.']
        );

        User::query()->updateOrCreate(
            ['email' => 'msett2004@gmail.com'],
            [
                'role_id' => $developerRole->id,
                'name' => 'Developer',
                'password' => Hash::make('12345678'),
            ]
        );

        collect([
            [
                'slug' => 'hero',
                'page_slug' => 'home',
                'name' => 'Primer bloque / Hero',
                'eyebrow' => 'Fine Jewelry • Est. 1994 • Guatemala',
                'title' => 'Mas que joyas, creamos historias.',
                'body' => 'Gabriela Salazar Jewelry es una joyeria premium fundada en 1994, especializada en joyas finas, diseno personalizado y piezas creadas para conservar recuerdos, emociones y legados.',
                'button_label' => 'Explorar servicios',
                'button_url' => '#servicios',
                'secondary_button_label' => 'Ver archivo visual',
                'secondary_button_url' => '#imagenes',
                'sort_order' => 1,
            ],
            [
                'slug' => 'products',
                'page_slug' => 'home',
                'name' => 'Productos destacados',
                'eyebrow' => 'Coleccion destacada',
                'title' => 'Piezas creadas para momentos que permanecen.',
                'body' => 'Una seleccion de joyas disponibles para inspirar la proxima compra.',
                'button_label' => 'Administrar productos',
                'button_url' => '/admin/products',
                'sort_order' => 2,
            ],
            [
                'slug' => 'history',
                'page_slug' => 'home',
                'name' => 'Historia',
                'eyebrow' => 'Historia y legado',
                'title' => 'Tres decadas creando simbolos memorables.',
                'body' => 'Desde 1994, la marca ha construido una reputacion basada en confianza, calidad y excelencia artesanal. Su combinacion de tradicion joyera, atencion personalizada y fabricacion propia mantiene viva una propuesta que trasciende generaciones.',
                'sort_order' => 3,
            ],
            [
                'slug' => 'purpose',
                'page_slug' => 'home',
                'name' => 'Proposito',
                'eyebrow' => 'Proposito',
                'title' => 'Joyas que conservan momentos.',
                'body' => 'Creemos que las joyas tienen el poder de guardar recuerdos, emociones y momentos que merecen ser recordados para siempre. Creamos simbolos de amor, exito, compromiso, familia y legado.',
                'sort_order' => 4,
            ],
            [
                'slug' => 'mission',
                'page_slug' => 'home',
                'name' => 'Mision',
                'eyebrow' => 'Mision',
                'title' => 'Calidad, elegancia y autenticidad.',
                'body' => 'Disenar, fabricar y ofrecer joyas de alta calidad que reflejen significado, autenticidad y experiencias memorables para cada cliente.',
                'sort_order' => 5,
            ],
            [
                'slug' => 'services',
                'page_slug' => 'home',
                'name' => 'Servicios',
                'eyebrow' => 'Modelo de negocio',
                'title' => 'Servicios de joyeria fina y alta joyeria.',
                'body' => 'Venta de joyeria fina, diseno personalizado, fabricacion propia, reparacion, restauracion y piezas exclusivas.',
                'sort_order' => 6,
            ],
            [
                'slug' => 'videos',
                'page_slug' => 'home',
                'name' => 'Videos',
                'eyebrow' => 'React integrado',
                'title' => 'Inspiracion en video.',
                'body' => 'Este modulo usa React para buscar entre videos de marca, servicios y contenido educativo. La busqueda actualiza la lista sin recargar la pagina.',
                'sort_order' => 7,
            ],
            [
                'slug' => 'values',
                'page_slug' => 'home',
                'name' => 'Valores',
                'eyebrow' => 'Personalidad y valores',
                'title' => 'Sofisticada, cercana, confiable y atemporal.',
                'body' => 'Integridad, excelencia, confianza, artesania, innovacion y legado guian cada relacion y cada pieza.',
                'sort_order' => 8,
            ],
            [
                'slug' => 'clients',
                'page_slug' => 'home',
                'name' => 'Cliente ideal',
                'eyebrow' => 'Cliente ideal',
                'title' => 'Joyas para quienes buscan significado, elegancia y confianza.',
                'body' => 'Mujeres y hombres de 25 a 65 anos que buscan elegancia, exclusividad, calidad, anillos de compromiso, regalos especiales y piezas con alto significado sentimental.',
                'sort_order' => 9,
            ],
            [
                'slug' => 'images',
                'page_slug' => 'home',
                'name' => 'Archivo visual',
                'eyebrow' => 'Archivo visual',
                'title' => 'Tabla para guardar imagenes de la marca.',
                'body' => 'Aqui podremos ir registrando imagenes de productos, campanas, packaging, redes sociales y materiales institucionales.',
                'sort_order' => 10,
            ],
            [
                'slug' => 'history-hero',
                'page_slug' => 'history',
                'name' => 'Hero Historia',
                'eyebrow' => 'Historia de la marca',
                'title' => 'Una joyeria construida sobre confianza, oficio y legado.',
                'body' => 'Gabriela Salazar Jewelry nacio en 1994 con la vision de crear joyas que representaran momentos unicos y significativos.',
                'sort_order' => 1,
            ],
            [
                'slug' => 'history-main',
                'page_slug' => 'history',
                'name' => 'Historia principal',
                'eyebrow' => 'Desde 1994',
                'title' => 'Mas de tres decadas acompanando historias.',
                'body' => 'La marca combina tradicion joyera, fabricacion propia y atencion personalizada para crear piezas que pueden trascender generaciones.',
                'sort_order' => 2,
            ],
            [
                'slug' => 'history-essence',
                'page_slug' => 'history',
                'name' => 'Esencia de marca',
                'eyebrow' => 'Esencia',
                'title' => 'Mas que joyas, creamos historias.',
                'body' => 'Disenamos simbolos de amor, exito, compromiso, familia y legado para clientes que valoran significado y calidad.',
                'sort_order' => 3,
            ],
            [
                'slug' => 'history-image-1',
                'page_slug' => 'history',
                'name' => 'Imagen Historia 1',
                'eyebrow' => 'Archivo visual',
                'title' => 'Taller y oficio',
                'body' => 'Espacio editable para mostrar imagenes del taller, proceso artesanal o detalles de fabricacion.',
                'sort_order' => 4,
            ],
            [
                'slug' => 'history-image-2',
                'page_slug' => 'history',
                'name' => 'Imagen Historia 2',
                'eyebrow' => 'Archivo visual',
                'title' => 'Piezas con historia',
                'body' => 'Espacio editable para mostrar joyas representativas de la trayectoria de la marca.',
                'sort_order' => 5,
            ],
            [
                'slug' => 'history-image-3',
                'page_slug' => 'history',
                'name' => 'Imagen Historia 3',
                'eyebrow' => 'Archivo visual',
                'title' => 'Atencion personalizada',
                'body' => 'Espacio editable para mostrar momentos de asesoria, seleccion de piezas o experiencia en tienda.',
                'sort_order' => 6,
            ],
            [
                'slug' => 'history-image-4',
                'page_slug' => 'history',
                'name' => 'Imagen Historia 4',
                'eyebrow' => 'Archivo visual',
                'title' => 'Legado familiar',
                'body' => 'Espacio editable para mostrar imagenes institucionales, generaciones o memorias de marca.',
                'sort_order' => 7,
            ],
            [
                'slug' => 'history-business-description',
                'page_slug' => 'history',
                'name' => 'Descripcion del negocio',
                'eyebrow' => 'Negocio',
                'title' => 'Descripcion del negocio',
                'body' => 'Gabriela Salazar Jewelry es una joyeria premium especializada en joyeria fina, diseno personalizado, fabricacion propia, reparacion, restauracion y piezas exclusivas para ocasiones especiales.',
                'sort_order' => 8,
            ],
            [
                'slug' => 'history-mission',
                'page_slug' => 'history',
                'name' => 'Mision',
                'eyebrow' => 'Mision',
                'title' => 'Mision',
                'body' => 'Disenar, fabricar y ofrecer joyas de la mas alta calidad que reflejen elegancia, significado y autenticidad, creando experiencias memorables y relaciones de confianza.',
                'sort_order' => 9,
            ],
            [
                'slug' => 'history-vision',
                'page_slug' => 'history',
                'name' => 'Vision',
                'eyebrow' => 'Vision',
                'title' => 'Vision',
                'body' => 'Convertirnos en una marca referente de joyeria fina en Latinoamerica, reconocida por legado familiar, excelencia artesanal, innovacion y piezas que trascienden generaciones.',
                'sort_order' => 10,
            ],
            [
                'slug' => 'history-values',
                'page_slug' => 'history',
                'name' => 'Valores',
                'eyebrow' => 'Valores',
                'title' => 'Valores',
                'body' => 'Nuestros valores orientan cada pieza y cada relacion: excelencia, personalizacion, artesania, confianza, atemporalidad, cercania y legado.',
                'sort_order' => 11,
            ],
            [
                'slug' => 'history-excellence',
                'page_slug' => 'history',
                'name' => 'Excelencia',
                'eyebrow' => 'Valor',
                'title' => 'Excelencia',
                'body' => 'Buscamos la perfeccion en cada detalle, desde la seleccion de materiales hasta el acabado final de cada joya.',
                'sort_order' => 12,
            ],
            [
                'slug' => 'history-personalization',
                'page_slug' => 'history',
                'name' => 'Personalizacion',
                'eyebrow' => 'Valor',
                'title' => 'Personalizacion',
                'body' => 'Cada cliente tiene una historia unica; por eso disenamos piezas que responden a su estilo, ocasion y significado personal.',
                'sort_order' => 13,
            ],
            [
                'slug' => 'history-craftsmanship',
                'page_slug' => 'history',
                'name' => 'Artesania',
                'eyebrow' => 'Valor',
                'title' => 'Artesania',
                'body' => 'Valoramos el trabajo hecho a mano con precision, paciencia y experiencia joyera.',
                'sort_order' => 14,
            ],
            [
                'slug' => 'history-trust',
                'page_slug' => 'history',
                'name' => 'Confianza',
                'eyebrow' => 'Valor',
                'title' => 'Confianza',
                'body' => 'Construimos relaciones duraderas basadas en transparencia, cumplimiento y acompanamiento cercano.',
                'sort_order' => 15,
            ],
            [
                'slug' => 'history-timelessness',
                'page_slug' => 'history',
                'name' => 'Atemporalidad',
                'eyebrow' => 'Valor',
                'title' => 'Atemporalidad',
                'body' => 'Creamos joyas elegantes que no dependen de tendencias pasajeras y pueden conservar su valor emocional a traves del tiempo.',
                'sort_order' => 16,
            ],
            [
                'slug' => 'history-closeness',
                'page_slug' => 'history',
                'name' => 'Cercania',
                'eyebrow' => 'Valor',
                'title' => 'Cercania',
                'body' => 'Acompanamos al cliente con una atencion humana, clara y personalizada en cada etapa del proceso.',
                'sort_order' => 17,
            ],
            [
                'slug' => 'history-legacy',
                'page_slug' => 'history',
                'name' => 'Legado',
                'eyebrow' => 'Valor',
                'title' => 'Legado',
                'body' => 'Disenamos piezas pensadas para permanecer, acompanando recuerdos y generaciones.',
                'sort_order' => 18,
            ],
            [
                'slug' => 'history-digital-project-objective',
                'page_slug' => 'history',
                'name' => 'Objetivo del proyecto digital',
                'eyebrow' => 'Proyecto digital',
                'title' => 'Objetivo del proyecto digital',
                'body' => 'Crear una plataforma digital elegante, administrable y clara que comunique la historia de la marca, muestre productos, capture solicitudes y facilite el seguimiento comercial.',
                'sort_order' => 19,
            ],
            [
                'slug' => 'catalog-hero',
                'page_slug' => 'catalog',
                'name' => 'Hero Catalogo',
                'eyebrow' => 'Catalogo de joyas',
                'title' => 'Piezas seleccionadas para celebrar momentos importantes.',
                'body' => 'Explora productos cargados desde el sistema administrativo con imagen, categoria y precio.',
                'sort_order' => 1,
            ],
            [
                'slug' => 'catalog-empty',
                'page_slug' => 'catalog',
                'name' => 'Mensaje catalogo vacio',
                'eyebrow' => 'Catalogo pendiente',
                'title' => 'Aun no hay productos publicados.',
                'body' => 'Cuando cargues productos desde el sistema apareceran en esta pagina.',
                'sort_order' => 2,
            ],
            [
                'slug' => 'collections-hero',
                'page_slug' => 'collections',
                'name' => 'Hero Galerias',
                'eyebrow' => 'Galerias de colecciones',
                'title' => 'Archivo visual de piezas, campanas y detalles de marca.',
                'body' => 'Una galeria alimentada desde la tabla de imagenes del sistema.',
                'sort_order' => 1,
            ],
            [
                'slug' => 'collections-empty',
                'page_slug' => 'collections',
                'name' => 'Mensaje galerias vacias',
                'eyebrow' => 'Galeria pendiente',
                'title' => 'Aun no hay imagenes activas.',
                'body' => 'Sube imagenes desde el sistema para alimentar esta galeria.',
                'sort_order' => 2,
            ],
            [
                'slug' => 'custom-made-hero',
                'page_slug' => 'custom-made',
                'name' => 'Hero Custom Made',
                'eyebrow' => 'Custom Made',
                'title' => 'Joyas hechas a la medida de una historia.',
                'body' => 'Disenamos piezas personalizadas desde la idea inicial hasta la fabricacion final, cuidando proporcion, significado y calidad.',
                'sort_order' => 1,
            ],
            [
                'slug' => 'custom-made-step-1',
                'page_slug' => 'custom-made',
                'name' => 'Paso 1',
                'eyebrow' => '1',
                'title' => 'Escuchamos',
                'body' => 'Entendemos la ocasion, estilo, presupuesto y significado de la pieza.',
                'sort_order' => 2,
            ],
            [
                'slug' => 'custom-made-step-2',
                'page_slug' => 'custom-made',
                'name' => 'Paso 2',
                'eyebrow' => '2',
                'title' => 'Disenamos',
                'body' => 'Traducimos la historia en una propuesta elegante, viable y duradera.',
                'sort_order' => 3,
            ],
            [
                'slug' => 'custom-made-step-3',
                'page_slug' => 'custom-made',
                'name' => 'Paso 3',
                'eyebrow' => '3',
                'title' => 'Fabricamos',
                'body' => 'Nuestro taller propio convierte el diseno en una joya lista para permanecer.',
                'sort_order' => 4,
            ],
            [
                'slug' => 'custom-request-hero',
                'page_slug' => 'custom-request',
                'name' => 'Hero Pieza personalizada',
                'eyebrow' => 'Piezas personalizadas',
                'title' => 'Cuentanos la joya que quieres crear.',
                'body' => 'Completa este formulario y el equipo revisara tu solicitud para iniciar una propuesta personalizada.',
                'sort_order' => 1,
            ],
            [
                'slug' => 'appointments-hero',
                'page_slug' => 'appointments',
                'name' => 'Hero Agenda de citas',
                'eyebrow' => 'Agenda de citas',
                'title' => 'Reserva un espacio para recibir asesoria personalizada.',
                'body' => 'Solicita una fecha y el equipo confirmara disponibilidad para atenderte con calma y detalle.',
                'sort_order' => 1,
            ],
            [
                'slug' => 'instagram-hero',
                'page_slug' => 'instagram',
                'name' => 'Hero Instagram',
                'eyebrow' => 'Instagram',
                'title' => 'Conecta con nuestras piezas, colecciones y momentos recientes.',
                'body' => 'Esta seccion queda lista para conectar un feed oficial de Instagram o dirigir a la cuenta de la marca.',
                'sort_order' => 1,
            ],
            [
                'slug' => 'instagram-main',
                'page_slug' => 'instagram',
                'name' => 'Bloque Instagram',
                'eyebrow' => 'Redes sociales',
                'title' => 'Gabriela Salazar Jewelry',
                'body' => 'Comparte lanzamientos, piezas personalizadas, anillos de compromiso, restauraciones y detalles del taller.',
                'button_label' => 'Abrir Instagram',
                'button_url' => 'https://www.instagram.com/',
                'sort_order' => 2,
            ],
            [
                'slug' => 'testimonials-hero',
                'page_slug' => 'testimonials',
                'name' => 'Hero Testimonios',
                'eyebrow' => 'Testimonios',
                'title' => 'Historias de clientes que confiaron en una pieza especial.',
                'body' => 'Cada testimonio refleja una experiencia de atencion, significado y joyeria hecha para permanecer.',
                'sort_order' => 1,
            ],
            [
                'slug' => 'testimonials-empty',
                'page_slug' => 'testimonials',
                'name' => 'Mensaje testimonios vacios',
                'eyebrow' => 'Pendiente',
                'title' => 'Aun no hay testimonios publicados.',
                'body' => 'Cuando se carguen testimonios activos apareceran en esta pagina.',
                'sort_order' => 2,
            ],
            [
                'slug' => 'contact-hero',
                'page_slug' => 'contact',
                'name' => 'Hero Contacto',
                'eyebrow' => 'Contacto',
                'title' => 'Hablemos de la joya, regalo o momento que quieres crear.',
                'body' => 'Envia tus datos y el equipo de Gabriela Salazar Jewelry te dara seguimiento.',
                'sort_order' => 1,
            ],
            [
                'slug' => 'contact-aside',
                'page_slug' => 'contact',
                'name' => 'Bloque lateral Contacto',
                'eyebrow' => 'Guatemala',
                'title' => 'Atencion cercana y especializada.',
                'body' => 'Usa este canal para consultas generales, seguimiento de piezas, anillos de compromiso, restauraciones o regalos especiales.',
                'sort_order' => 2,
            ],
        ])->each(function (array $block): void {
            HomeBlock::query()->updateOrCreate(
                ['slug' => $block['slug']],
                $block + ['page_slug' => 'home', 'is_active' => true]
            );
        });

        collect([
            [
                'client_name' => 'Cliente Gabriela Salazar',
                'occasion' => 'Anillo de compromiso',
                'quote' => 'Nos guiaron con paciencia y claridad hasta encontrar una pieza con verdadero significado.',
                'sort_order' => 1,
            ],
            [
                'client_name' => 'Familia S.',
                'occasion' => 'Restauracion',
                'quote' => 'Una joya familiar recupero su brillo sin perder su historia.',
                'sort_order' => 2,
            ],
            [
                'client_name' => 'Cliente especial',
                'occasion' => 'Custom Made',
                'quote' => 'El proceso personalizado hizo que la pieza se sintiera unica desde el primer boceto.',
                'sort_order' => 3,
            ],
        ])->each(function (array $testimonial): void {
            Testimonial::query()->updateOrCreate(
                [
                    'client_name' => $testimonial['client_name'],
                    'occasion' => $testimonial['occasion'],
                ],
                $testimonial + ['is_active' => true]
            );
        });
    }
}
